### ISSUE TITLE
Custom items that use tools as their base are missing

### ISSUE THREAD

**Issue by AloXado320** [JustAHuman-xD/EasyItemList#2]
![image](https://github.com/user-attachments/assets/923dc142-b456-4b6a-a409-f4697b25e338)
This server has special items that make use of custom model data on tools, most of the custom items use diamond hoe as a base for them (see inventory for examples), the server is in spanish but I'm not sure if I should share it here

**Comment by JustAHuman-xD** [comment]
Are the items craftable in any vanilla recipe block? Like properly registered?

**Comment by AloXado320** [comment]
They aren't craftable, they have a custom item model and some have descriptions and custom names

**Comment by JustAHuman-xD** [comment]
> They aren't craftable, they have a custom item model and some have descriptions and custom names

Then that's why. EasyItemList detects items from recipes, so if its not in a recipe (aka craftable), it wont be detected and added
