### ISSUE TITLE
1.19.4 Crash without any errors...?

### ISSUE THREAD

**Issue by 0Starocean0** [JustAHuman-xD/EasyItemList#3]
The mod version is 0.1.3-1.19.4
log: https://mclo.gs/bf26uBn

**Comment by JustAHuman-xD** [comment]
And you're sure it's only crashing due to this mod? No crash reports nothing in the log?

**Comment by 0Starocean0** [comment]
> And you're sure it's only crashing due to this mod? No crash reports nothing in the log?

https://mclo.gs/PmzL2bz

**Comment by JustAHuman-xD** [comment]
> > And you're sure it's only crashing due to this mod? No crash reports nothing in the log?
> 
> 
> 
> https://mclo.gs/PmzL2bz

Found the issue, you need architectury api, I apparently forgot to mark it as a dependency on modrinth and curseforge (which I have since fixed), but if you add it it'll start working, once you can confirm that I'll close this
